# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6adbde71b214b5ee42df7cb7d5c74afdf07dcc0d242f364123b0afedb75d7d6a49ee0c5c107844861fed01ddd08ce65de75a71fd2a44be282e756a3f15a186e6

test:
  secret_key_base: 7c364802e614945c079bbb4150c1707104355ca01a0da978d884d386df7a9ed46ba9416ba15595d9c9697c8e77318cddb389af86a1fcee39c8e3231f13cf34e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
